Env issue test 12

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,5 +1,5 @@
 name: GitHub Actions Demo
-on: [push]
+on: [ push ]
 jobs:
   tests:
     runs-on: ubuntu-latest
@@ -24,7 +24,7 @@ jobs:
 
   docker-image:
     runs-on: ubuntu-latest
-    needs: [tests]
+    needs: [ tests ]
     steps:
       - name: checkout repo
         uses: actions/checkout@v2
@@ -48,8 +48,8 @@ jobs:
           shell: bash
           run: |
             bash startup.sh &
-            [ $(curl -I http://127.0.0.1:8080 2>/dev/null | head -n 1 | cut -d$' ' -f2) -eq 200 ]
-            [ $(curl -I http://127.0.0.1:3000 2>/dev/null | head -n 1 | cut -d$' ' -f2) -eq 200 ]
+            if [ $(curl -I http://127.0.0.1:8080 2>/dev/null | head -n 1 | cut -d$' ' -f2) -ne 200 ]; then echo "Frontend server error" && exit 1; fi
+            if [ $(curl -I http://127.0.0.1:3000 2>/dev/null | head -n 1 | cut -d$' ' -f2) -ne 200 ]; then echo "Backend server error" && exit 1; fi
 #  app-tests:
 #    runs-on: ubuntu-latest
 #    needs:
